"""
Functionallity encalsulated in hte method format_pagerank_dict()

There must be always a return, but it could also happen to have some other
outputs of different type. Ex: result to a file.

"""

class PageRankFormatterInterface(object):

    def __init__(self):
        pass


    def format_pagerank_dict(self, a_dict):
        """
        It receives a dict generated by ng.algorithms.pagerank() and returns it in a given format
        :param a_dict:
        :return:
        """
        raise NotImplementedError()